Repository SKNETWORKS-FAMILY-AICAMP/SKN09-FINAL-3Team, pull requests merged in 2025-05, with the labels that each got.

#14 Del: Test Data
  test.py
  test_law_vector_db.py
Labels: del

#22 23 add minimal requirementstxt for essential dependencies
  pass_project/requirements.txt
Labels: fix

#27 Add: PASS Editor UI Implementation
  pass_project/app/forms.py
  pass_project/app/static/app/editor.css
  pass_project/app/static/app/editor.js
  pass_project/app/static/app/images/logo.png
  pass_project/app/static/app/images/user-avatar.png
  pass_project/app/templates/app/editor.html
  pass_project/app/templatetags/__init__.py
  pass_project/app/templatetags/form_tags.py
  pass_project/manage.py
Labels: Feature
